language: node_js
node_js: '8'
before_script: npm install -g wcfutils
script: wcfutils
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.pages.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com/
  - secure: V4LbfCkfqk73GUIyMkarCmtR9+hFINNxfR3+35keCrvyz5JYlTJoOIpb2PcV90N4Qee682TiZuu2EokLU4yud19Fsid5xyaLMI/EDR6jwWwA91BE+SZQlyVOjDiwa6gYMUEiJRV3Y2IRJGP7ZVGTVog1OVIiMK/dZcjdK4g1HuWFRRMNlRS3Tn8ZPbK+MlzvDlODMSBxeAUb0lPamYh0xvJ02vGL+oXgtSGQVrejzM/yXzX7NRMhIlp0xjgL9n9WxBD8LTmsS6tZBOQQ2jlm6xZi/XwNBwYzZ/Z+d3Ecn/w27DbDX7hl+pJQEcuRZE12TQSdsrKaeY9hG5dPkbgNCG1+65CJGtoGYMz6c2gNEyh603BwXvcZPD/62EgsKtlplmfm2lFRPSbz/rvBmIuYhGtCeqNzR6kdUNDWwgQNaMUht+V/XRz6i4SQwNgQKtZw7h16BRAwcE3OxyWsSq1QPpuW3Xn+FaRR+rbCzULa8JbzDJRVra7S7GU3igudV1OFS8vTW9fvXzkCjUMSHXe9t7zWcvtc3F8dD34abHQlEec3IvnXHgYo3Trho5Lcq5NvZxPgqw0te0DhSL3+b2QjJozMgdVChoN4GN1UeFeqA+z3AIs38pU1BydtI5L2yxT7zkfybD1o0c8qymF1VxGJBEA3v6CKczlwryWFDfz4qco=
  - secure: FPxGPnw12lUbeio8KNmjvvVrKyHo+AZvza9T2w2MIhB/5VhpHF5Mft4l3aP97607EwNqPcLPrdcFr3K0Zn2llgqebjdgton/YnZXb544S5En5OUaOeyjjhyq54ucXnBmPGgd1ylF74MzrncDFKFasofh6ZT1b6/MWDvMEkvYKlndGmCFvFgMQlAWEaLRzrFZar5xl2sxAKYa235864rWpR9LlWLyeGwl+dGQjMnak6ql8TC9lVWf3x9gxkVQiiVgIc7H4IfbrlibY5eNg95hmR2d3NiK++rIkJvJVQ+oB/aPs/XjGDPdPz3c5+kv9095VdaFngta13yFMSYnHOnGtJMXvC/KcwvWsXfXmTCCftMItNFf1myBsWpAlmwMvgnvdO99M31m/7XW1H7vaSoHrR8uQSYkJDH4fZJUzZFSK8aprBlVVRw0aaYJp4wiJrbQHhOp4PvAGKN3dCwkHTK2bXsnaEmqhrzDLkO6/3Dt/j0ryJSTMmVuPu3pm4xXQ39UcGgGKd3B7Qtt02D4NPWcBZ3OeKYF0iFWcH0qG/Hn6nf8Sn+nyHcDddRgQgu00zor4eacba6bQiAgbmgHdO47lDhRTO3DnPVwU8NfIsEKfAKjGZaNVp8orMND1BiZPjKNkvLSAmKkztYxT3ySaWRlCnESCKb6RrlZYtxcsbvHoO4=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
